SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE DATABASE IF NOT EXISTS `SME` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `SME`;

DROP TABLE IF EXISTS `SME`;
CREATE TABLE IF NOT EXISTS `user` (
  `loanID` int(6) NULL,
  `CID` int(6) NOT NULL,
  `cName` varchar(128) NOT NULL,
  `employees` varchar(128) NOT NULL,
  `revenue` int(255) NOT NULL,
  `assets` int(255) NOT NULL,
  `industry` varchar(128) NOT NULL,
  PRIMARY KEY (`CID`)
  );

    